[package]
name = "dayquest_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
figment = { version = "0.10.19", features = ["json", "serde_json"] }
serde = "1.0.210"
serenity = "0.12.2"
tokio = { version = "1.40.0", features = ["full"] }
